apiVersion: v1
kind: Pod
metadata:
  name: nginx-cd
  namespace: default
spec:
  containers:
   - name: nginx
     image: nginx:1.14.2
     ports:
      - containerPort: 80
  initContainers:
  - name: waitfordns
    image: busybox:1.28
    command:
      - sh
      - -c
      - until nslookup mymysql; do echo "trying to resolve..."; sleep 1; done

