apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: nginx-blue
  name: nginx-blue
  namespace: default
spec:
  replicas: 10
  selector: 
    matchLabels:
      app: nginx-blue
    template:
      metadata:
        labels:
          app: nginx-blue
      spec:
        containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: nginx-green
  name: nginx-green
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx-green
    spec:
      containers:
      - image: httpd
        imagePullPolicy: Always
        name: httpd

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec: 
  ports:
  - port: 80
  selector:
    app: nginx-green
  type: ClusterIP



